# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e2693edfc408a94abe075b88c4cf2247af170477657131434cb8c917bd3f0eeb1f5cde8a3fa96f05aba77f10b7efbe775444ccfc4007233990ca7706c75edb0

test:
  secret_key_base: ccf3b5120140a5ed8ae8ef881b92feb1ecc903f8f1d3ccb82efd33880a4dd02937e76f4cb90eb80ad3b91df0d359eaa20311ce0f932ba7b1f633be02b71d0695

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
